require ("usr.options")
require("usr.keymaps")
require("usr.plugins")
require("usr.cmp")
require("usr.lsp")
require("usr.telescope")
require("usr.treesitter")
require("usr.autopairs")
require("usr.gitsigns")
require("usr.comments")
require("usr.toggleterm")
-- require("usr.flutter-tools")